version: "3.8"

services:

  postgres:
    image: postgres:16
    container_name: mini_postgres
    environment:
      POSTGRES_DB: minigame
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: ["start-dev"]
    ports:
      - "8083:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    depends_on:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: mini_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  keycloak_data: